# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 470)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.PenWidthSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.PenWidthSpinBox.setGeometry(QtCore.QRect(90, 10, 61, 22))
        self.PenWidthSpinBox.setProperty("value", 5)
        self.PenWidthSpinBox.setObjectName("PenWidthSpinBox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 11, 54, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 10, 71, 20))
        self.label_2.setObjectName("label_2")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(430, 15, 71, 16))
        self.checkBox.setChecked(True)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.MaskComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.MaskComboBox.setGeometry(QtCore.QRect(260, 10, 69, 22))
        self.MaskComboBox.setObjectName("MaskComboBox")
        self.MaskComboBox.addItem("")
        self.MaskComboBox.addItem("")
        self.MaskComboBox.addItem("")
        self.MaskComboBox.addItem("")
        self.MaskComboBox.addItem("")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(520, 15, 71, 16))
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setTristate(False)
        self.checkBox_2.setObjectName("checkBox_2")
        self.AnnotationView = QtWidgets.QGraphicsView(self.centralwidget)
        self.AnnotationView.setGeometry(QtCore.QRect(420, 50, 360, 360))
        self.AnnotationView.setObjectName("AnnotationView")
        self.ImageView = PaintView(self.centralwidget)
        self.ImageView.setGeometry(QtCore.QRect(20, 50, 360, 360))
        self.ImageView.setObjectName("ImageView")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(630, 15, 131, 20))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_image = QtWidgets.QAction(MainWindow)
        self.action_image.setObjectName("action_image")
        self.action_mask = QtWidgets.QAction(MainWindow)
        self.action_mask.setObjectName("action_mask")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.menu.addAction(self.action_image)
        self.menu.addSeparator()
        self.menu.addAction(self.action_2)
        self.menu.addAction(self.action_3)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.MaskComboBox.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Vessel Marker v1.01"))
        self.label.setText(_translate("MainWindow", "笔刷大小:"))
        self.label_2.setText(_translate("MainWindow", "mask透明度:"))
        self.checkBox.setText(_translate("MainWindow", "视角跟随"))
        self.MaskComboBox.setItemText(0, _translate("MainWindow", "0%"))
        self.MaskComboBox.setItemText(1, _translate("MainWindow", "25%"))
        self.MaskComboBox.setItemText(2, _translate("MainWindow", "50%"))
        self.MaskComboBox.setItemText(3, _translate("MainWindow", "75%"))
        self.MaskComboBox.setItemText(4, _translate("MainWindow", "100%"))
        self.checkBox_2.setText(_translate("MainWindow", "拖拽模式"))
        self.label_3.setText(_translate("MainWindow", "Tips:  ctrl+左键 画图"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.action_image.setText(_translate("MainWindow", "打开image和mask"))
        self.action_mask.setText(_translate("MainWindow", "打开mask"))
        self.action_2.setText(_translate("MainWindow", "存储 标记图片"))
        self.action_3.setText(_translate("MainWindow", "存储 透明png"))
from PaintView import PaintView
